### ISSUE TITLE
Empty file/folder timeout

### ISSUE THREAD

**Issue by AuHau** [MainframeHQ/erebos#125]
I am treating edge-cases and have stumbled on some weird behavior, where I tried to simulate uploading an empty folder, which might actually mean uploading an empty file. Swarm gets stuck and the call times out.

I am trying to upload this structure:
```js
 const dir = {
      [`foo-${uploadContent}.txt`]: {
        data: '',
      }
 }
``` 

I wanted to ask you @PaulLeCam first on your input if I am missing something. Before reporting it to Swarm. 

I have created PR with test-case: https://github.com/MainframeHQ/erebos/pull/124

**Comment by PaulLeCam** [comment]
There is no specific logic related to this in Erebos so I think you should check the Swarm implementation to know the expected behavior.
It could be useful to try to reproduce the issue using `curl` or another HTTP client to help identify if the behavior is caused by Erebos or an underlying library, or consistent cross-client.

**Comment by AuHau** [comment]
Hmm reproduced it with `curl` so I will report it straight to Swarm. Thanks!

**Comment by AuHau** [comment]
https://github.com/ethersphere/swarm/issues/1995
