### ISSUE TITLE
Streams, streams, streams (again)

### ISSUE THREAD

**Issue by AuHau** [MainframeHQ/erebos#133]
So as I was integrating the stream support to our project I have stumbled on few things relating to stream support that I did not realize when writing the original PR.

### `uploadDirectory()`

Currently, the `DirectoryData` interface does not support streams. I bypassed that with uploading `tar` bundle that I have packed using the `tar-stream` library. When I was writing PR to add this functionality to Erebos I have realized that I am not sure how this approach works with Content Types as there is no content-type specified. Does anybody have some idea?

I assume this should maybe somehow solved by Swarm? Because this is already used in Erebos in the Node version that supports uploading directories using `uploadDirectoryFrom()` call that bundles the files using `tar-fs`... Is it handled or is it just left on its own? A.k.a using sniffers to determine the content-type without availability for the user to override this?

### Streaming directory download

I forgot about support for download stream of directories. You can work around it but I would argue this should be natively supported by Erebos.

The problem is that the current directory data structure is not really streaming-friendly, because the whole directory's content needs to be buffered in order to construct the object. For example `js-ipfs` handles this having stream in object mode that yields an object for each directory entry (see [their docs](https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/FILES.md#getreadablestream)) and I would propose to follow a similar approach. Any comments on it?

**Comment by AuHau** [comment]
Small update about this. Apparently, according to janos it is possible to specify content-type inside tar using extended attribute `user.swarm.content-type`.

Problem is that `tar-stream` that is currently used in this library does not seem to support extended attributes. I have created issue regarding that: https://github.com/mafintosh/tar-stream/issues/108

The alternative is to use [node-tar](https://github.com/npm/node-tar), which according to `tar-stream` is less performant, but it supports extended attributes.

**Comment by PaulLeCam** [comment]
To me the "ideal" way to achieve this would be to have Swarm APIs to create and edit manifests.
Instead of having to use tar or buffer all the data when using `uploadDirectoryData()`, it would allow the client to simply upload files as needed, and then as needed create a manifest by providing the raw Swarm hash and additional metadata such as the content type.

Regarding using `node-tar` instead of `tar-stream` I think beyond the speed we should consider the browser bundle size as discussed in https://github.com/MainframeHQ/erebos/issues/134 and if it supports the same functionalities as [`tar-fs`](https://github.com/mafintosh/tar-fs) (that is needed in `api-bzz-node` and uses `tar-stream`)?

Beyond that I'd like to be more cautious about adding/changing dependencies in `api-bzz-base` and try to support edge-cases like this. The `upload()` method now supports being provided a stream, so the application could handle creating the tar as needed without having Erebos need to provide first-class support for it in browser in my opinion.

**Comment by AuHau** [comment]
Well as it seems that support for streams is not a priority in Erebos I am closing this as well.
