### ISSUE TITLE
Browser bundle size problems - rjxs

### ISSUE THREAD

**Issue by AuHau** [MainframeHQ/erebos#134]
As I was preparing the first release of our library I noticed that our browser bundle was quite drastically huge (1,2MB) and started to do some analysis. I have found out that from Erebos we brought in `rjxs` dependency which takes around 197kB (~16%) of the bundle size. To me this is too much especially since we don't use it at all.

From my understanding, it is used only for its `Observable` function (at least in the `api-bzz` part). Do you know if it is either possible to customize `rjxs` bundle to bundle only this part and drop rest?

Or what would be your thoughts to drop the `Observable` support in favor of browser bundle size? I think that since now there is the support of streams I don't think `Observable` is really needed anymore.

**Comment by PaulLeCam** [comment]
`rxjs` isn't used only for its `Observable` class, it's used for all the flow logic related to polling feeds. It's also used in other Erebos packages so I don't think it would be beneficial to try to remove it from `api-bzz-base` anyways.

Regarding the bundle size I think it's caused by the switch to webpack in v0.11: in v0.10 the size of `erebos.swarm.production.js` (included in `@erebos/swarm-browser`) is 93944 bytes and it jumps to 242398 bytes in v0.11.
My guess is that either webpack doesn't handle ESM imports as well as Rollup does, or adding the `readable-stream` and `tar-stream` dependencies cause this much increase, so I'd rather remove these from the `api-bzz-base` package and provide the functionality in another package that could be installed separately.

Thinking about bundle size further, I think the `api-bzz` packages could even be split further, between Swarm "basic" functionalities (immutable data), feeds (that adds the `rxjs` and `@erebos/keccak256` dependencies) and Node streams support (adding the `readable-stream` and `tar-stream` dependencies), so it would be more granular to support various application needs, what do you think?

**Comment by AuHau** [comment]
Oh I did not know about the other usages, sorry. Well, that makes more sense. 

Yeah, you are right there is definitely some improvement space regarding the Webpack build setup. I am unfortunately not an expert in this area. I think we might focus on this part in the future, so I guess as part of that endeavor I will tackle the build process here as well, but I can't estimate when that gonna be.

Well, I would agree with the separation of feeds, but I admit I might be biased here as I would like to see the `rjxs` out of the scope 😅Also not quite sure what is the position of the feeds as I do not use them, so I think you or somebody who was general overview of Swarm should evaluate that.

But I am strongly against removing the `readable-stream` and `tar-stream`. They provide functionality that I would consider as part of the "core" `bzz` functionality. `Directory` handling is definitely needed and for that `tar-stream` is needed as well and with that need for `readable-stream` is needed as well for browser. Btw. `readable-stream` is only browser specific as it is "mock" of Node's `stream` package 😉

**Comment by PaulLeCam** [comment]
I started splitting out the `bzz` modules into the following:
- `bzz` contains the core functionalities with no dependency, it could be enough for some browser apps
- `bzz-browser` extends `bzz` with methods to upload and download directories, it adds the `tar-stream` dependency but eventually that could be replace by a browser implementation if available
- `bzz-node` adds the `node-fetch` and `form-data` dependencies needed to extend `bzz` for node
- `bzz-feed` contains the feed-related methods
- `bzz-fs` contains the FS-related methods when using node

So doing this `readable-stream` is still a transitive dependency in `bzz-browser` because it uses `tar-stream` but it should get easier to remove, especially since it's only needed to extract files from the tar.
Eventually that should allow to package the library using rollup rather than webpack because from my understanding the fundamental issue is the circular dependency in `readable-stream`.

**Comment by AuHau** [comment]
Soo if I understand it right you want to remove `stream` support for browser? To remove the `downloadStream()` method and generally remove the capability of downloading directory structures in browsers?

**Comment by PaulLeCam** [comment]
Yes to removing `downloadStream()`, you can simply use the response body when calling `download()` anyways if needed, and that will return the platform-specific readable stream: [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) in browser and [Readable](https://nodejs.org/dist/latest/docs/api/stream.html#stream_class_stream_readable) in node.

No to removing the capability of downloading directory structures in browsers, but you'll need to use `@erebos/bzz-browser` for this, as it adds the `tar-stream` dependency. Using simply `@erebos/bzz` it won't be provided.

**Comment by AuHau** [comment]
Hmm, this is unfortunate. For us having isomorphic API is important together with the support of streams.

Well, I am closing this as the new level of break down of the packages offers better dependency management.
