### ISSUE TITLE
Implement Feedlinks Protocol

### ISSUE THREAD

**Issue by camronlevanger** [MainframeHQ/erebos#82]
# Feedlinks

In order to support the idea of realtime feeds and persistent pss, it is proposed that we gravitate towards an informal standard we have dubbed "feedlinks".

After discussing the use case with the broader Swarm community we have reached general consensus on the first iteration of the implementation.

## The Proposed Solution

- The content of messages will be stored in Swarm in represented as JSON.
- The BZZ hash of the stored content will then be posted to Swarm Feeds.
- The content will include a pointer to the previous message hash creating a singly linked list allowing traversal independent of Swarm functionality.

## The Proposed Protocol Format

```
{
  "protocol": "feedlinks",
  "version": 1,
  "id": "ff473a167f456e839186b9ef391d344b7b14fa13877fe2b0075863a4755f2e9f",
  "timestamp": 1545233446,
  "references": [
    "fg584a167f456e839186b9ef391d344b7b14fa13877fe2b0075863a4755f2e9g",
    "f9473a167f456e839186b9ef391d344b7b14fa13877fe2b0075863a9855f2e9f"
  ],
  "previous": "fb473a169f456e839186b9ef391d344b7b14fa13877fe2b0075863a4755f2e9a",
  "type": "application/json",
  "author": "0x2013dfc464e594318cd8353f695e1f2b61f4e824",
  "content": {
    "any": "random",
    "data": "type",
    "we": "support"
  }
}
```

## Content Type

The content type stored in the `content` attribute will be indicated by the `type` attribute.

It is the responsibility of the higher level code (not the protocol implementation) to handle the encoding and decoding of content types.

## Questions

What is `id` for if unable to retrieve the hash before upload?
Inclusion of the `protocol` attribute?

**Comment by PaulLeCam** [comment]
Thanks for putting this together!

One question regarding the `version` field, should it be `int` or `float`? I think from the Go struct you shared it was an `int`, wasn't it?

Also regarding the `timestamp`, this is in seconds, isn't it? JS use milliseconds by default so we just need to make sure the implementation does the conversion to match the format we define.

**Comment by camronlevanger** [comment]
@PaulLeCam yes, version should be `int`. I will update.

The timestamp is in seconds. I would prefer it to be milliseconds, but either way I'll make sure it's handled properly.

**Comment by agazso** [comment]
I'm trying to implement something similar in my app and I would like my design to converge to Feedlinks as much as possible. It's not clear to me from the description what are the hashes exactly.

To my understanding there are be two types of meaningful hashes here: the hash of the content (`ContentHash`) and the hash of the Feedlink itself (`FeedlinkHash`).

I assume that the types of `previous` and `references` are `FeedlinkHash` and they are set to the hash of the previous Feedlink and other Feelinks.

My question is what exactly the `id` is? I assume that it is the hash of the content, because the other option would be the hash of the Feedlink itself, but then the definition would be circular. If it is the hash of the content in my opinion 'contentId` or `contentHash` would be a more descriptive name.

Another question comes up then: what's the proposed way to calculate the hash of the content? Do you upload it to Swarm first?

**Comment by PaulLeCam** [comment]
Yes the `previous` field represents the Swarm hash of the previous link. It is needed by the protocol in order to iterate.
Regarding the other fields, if I remember correctly the purpose of the `id` was more to support an application-level ID, rather than something needed by the protocol, and `references` could be other links that are relevant, but again more as something for the application.

I think @camronlevanger might the the best suited to answer these questions as he discussed this with Javier.

**Comment by jpeletier** [comment]
This structure is very similar to what we use in Ethergit, I guess it comes from my conversation with @camronlevanger.

When we came up with this concept we named it "Timeline", and we call each of these JSONs a "Chapter" in a timeline. We wanted to avoid the overused "link", "block" or "chain" words in our crypto world. If you renamed Feedlinks to Timeline, that would honor me.

Here are the answers to all questions I have seen so far in this thread:

> What is id for if unable to retrieve the hash before upload?

The `id` is not supposed to be serialized. However, once you fetch the Chapter off Swarm, it is handy to populate this field with the Swarm hash you used to retrieve it. In the original Go structure: 

```go
type Chapter struct {
    ID         EGID            `json:"-"`
    Version    int             `json:"version"`
    Timestamp  uint64          `json:"timestamp"`
    References EGID            `json:"references"`
    Previous   EGID            `json:"previous,omitempty"`
    Type       ContentType     `json:"type"`
    Content    json.RawMessage `json:"content"`
    Author     *User           `json:"author"`
}
```
... `ID` is `json:"-"`, meaning it is a value that is not serialized. `EGID` is just an hex string type in our app.

> Inclusion of the protocol attribute?

OK with me, but maybe not so important since the application should know what to expect when looking up a feed.

> `version` field type

I think this should stay an int.

> `timestamp` field unit.

Originally, this field is in seconds because it was convenient to work with in Go. I'm OK with it in milliseconds.

> @agazso: *To my understanding there are be two types of meaningful hashes here: the hash of the content (ContentHash) and the hash of the Feedlink itself (FeedlinkHash)*

There is only Content Hash, or "Chapter ID", which is the Swarm hash of the entire JSON structure, `id` field removed. So you upload this JSON (without `id` field) to Swarm (**Important: upload to `bzz-raw:`, not to `bzz:` !!**) and you get a hash: That's the `id`, Chapter ID.

> @agazso: *I assume that the types of previous and references are FeedlinkHash and they are set to the hash of the previous Feedlink and other Feedlinks*

The types of `previous` and `references` are simply the Swarm Hashes / Chapter IDs of other Chapters, so you can just retrieve those from Swarm, following the Timeline.

**Comment by jpeletier** [comment]
As additional feedback, I would add an optional  `signature` field for an additional level of security.

This would be the Ethereum ECDSA signature of this JSON, serialized without whitespace and obviously without the `id` and `signature` fields themselves.

Once the signature has been calculated, the `signature` field is added and the result is uploaded to `bzz-raw:` to obtain the Chapter ID.

**Comment by PaulLeCam** [comment]
Thanks for the feedback!

Thanks for the explanations regarding the `id` field, it makes sense. I'll update the implementation to reflect this.
About the `references`, are there specific rules/constraints attached to this field please? For example should these be the chapter IDs right before the `previous` value, or could these be "stepping" ones, for example accumulated every 20 chapters as a hint of how many chapters there are in the timeline and a way to quickly access specific ones?

Regarding the nomenclature I like the Timeline and Chapter terms, I agree it would be good to use terms that are not confusing with the rest of the ecosystem. @camronlevanger if I remember well you were the one suggesting "Feedlinks", are you OK with the suggested changes?

Also, I'm curious why it is important to upload using `bzz-raw` rather than `bzz` please? Is it to avoid extra resolution logic on Swarm?
In the current implementation I'm using `bzz` and I think it has the advantage for usability of being able to load a chapter using its hash or the "timeline hash" (using a feed manifest) retrieving the latest chapter indifferently.
One practical use case I have for it is the ability to load a range of chapters between the provided latest and oldest chapter IDs. As you can see in [this test case](https://github.com/MainframeHQ/erebos/blob/feedlinks/__tests__/feedlinks.js#L210-L214) the implementation also supports providing the feed/timeline hash as the latest chapter ID, so it makes it easy to sync an app between the last known chapter and the latest one.

Regarding the `protocol` field, I think when we discussed this with Camron and Shane the idea was to have a way to type-check the payload and make sure it is a valid chapter before performing any additional logic, but I don't mind getting rid of it if we work with the assumption the data should always be chapters anyways.
For the `timestamp` I don't mind having it in seconds if it simplifies the implementation in other languages, I think JS is more the exception than the rule using millisecond timestamps.

I like the idea of supporting signatures, what format should they be stored in? A hex string prefixed with `0x`? An array of bytes?

@camronlevanger @howleysv any other comments/feedback please?

**Comment by jpeletier** [comment]
> About the references, are there specific rules/constraints attached to this field please?

There are no restrictions. The goal of the `references` field is just to link to related chapters in the current timeline or another. For example, if you were using a timeline to model a series of forum posts, you could use `references` to indicate a previous chapter post this post is replying to. Forcibly, these referenced chapters happen in the past, otherwise you couldn't possibly have their `id`.

> Also, I'm curious why it is important to upload using bzz-raw rather than bzz please? [...]

`bzz` is much slower than `bzz-raw` since what you'll get is just a JSON that gives you the final hash plus a content-type which you already know it is a JSON. This will slow down your timeline scan significantly and make it more error prone (manifest lookup must succeed as well).

> In the current implementation I'm using bzz and I think it has the advantage for usability of being able to load a chapter using its hash or the "timeline hash" (using a feed manifest) retrieving the latest chapter indifferently.

This is a very expensive price to pay for that convenience. In my experience, I have not found a use for Feed manifests other than putting their hash in ENS for website resolution. For any other app, in practicality you access the feed by supplying a `Topic` and a `User`. For a forum application, `Topic` could be "discussion" and `User` would be for example Alice's ethereum address. Thus, you don't need to publish a manifest to access someone's timeline and start downloading chapters. You just need to agree on a topic. For example, in Ethergit, the topic is "ethergit:timeline:<repository>"; this retrieves the id (Swarm hash) of the last published chapter of any user who is participating in that repository.

> One practical use case I have for it is the ability to load a range of chapters between the provided latest and oldest chapter IDs. As you can see in this test case the implementation also supports providing the feed/timeline hash as the latest chapter ID, so it makes it easy to sync an app between the last known chapter and the latest one.

You can do that with `bzz-raw` also.

> Regarding the protocol field, I think when we discussed this with Camron and Shane the idea was to have a way to type-check the payload and make sure it is a valid chapter before performing any additional logic, but I don't mind getting rid of it if we work with the assumption the data should always be chapters anyways.

ok

> For the timestamp I don't mind having it in seconds if it simplifies the implementation in other languages, I think JS is more the exception than the rule using millisecond timestamps.

Lets convene on using milliseconds as the 1s resolution may not be enough precision for some applications updating a timeline in bursts.

> I like the idea of supporting signatures, what format should they be stored in? A hex string prefixed with 0x? An array of bytes?

This would be a hex string prefixed with `0x` so it is the same as signatures in Swarm.

**Comment by PaulLeCam** [comment]
Thanks for the explanations!
I'm updating the implementation to reflect these changes and see how it goes.

**Comment by camronlevanger** [comment]
Thanks for jumping in @jpeletier. @PaulLeCam I like the Timeline/Chapters terminology. I think @howleysv may have had other reasoning behind adding the protocol field, but I can't recall the details right now.

**Comment by howleysv** [comment]
Sorry for the delay in giving feedback.

I think the idea with `protocol` was in case you wanted to fork the protocol and add your own fields or change existing fields, it would stop you getting too far into the stream before finding out your client is incompatible.

Regarding `version`, there was also discussion around making it a semver string eg `1.0.0` rather than integer. The idea was that you could indicate forward compatibility between versions, which could be useful since you can't force updates, you can't migrate data, and these structures are designed to be reasonably long-lived. Major version numbers would indicate breaking changes, minor would be new functionality that doesn't break existing clients, patch for minor tweaks. So a client that only knows about `1.0.0` would be able to follow chapters written with `1.2.3` but shouldn't try to interpret chapters using `2.0.0`.

If we don't like semver, most of the useful functionality could also be achieved with an additional `minVersion` integer field to show the lowest protocol version that can read chapters of the current version protocol. Or if we don't like multiple version fields, both versions could be packed into a single int?

**Comment by jpeletier** [comment]
I'm OK with a semver string, makes sense.

**Comment by PaulLeCam** [comment]
I'll update with semver, good idea!

Regarding the `protocol`, maybe we could define how it can be extended? For example could it be `timeline/ethergit` and `timeline/mainframe` assuming we add custom "vendor" fields or rules for `references` for example, or something more like `timeline+git`, `timeline+json-ld+did`, etc. as "standard" sub-protocols that could be handled by other libraries in a generic way?

**Comment by PaulLeCam** [comment]
I updated the implementation to expect the `protocol` value to start with `timeline` (so other values could be accepted) and the `version` to be a semver string.

Regarding signatures support, providing the `encode()` and/or `decode()` functions should cover the use case as in this test: https://github.com/MainframeHQ/erebos/blob/132511b7a66563631db48af369540462e4af7e57/__tests__/timeline.js#L96-L110
This should also allow for other use cases such as validation and encryption.

I added documentation for the [implementation API](https://github.com/MainframeHQ/erebos/blob/132511b7a66563631db48af369540462e4af7e57/docs/timeline-api.md), [protocol specification](https://github.com/MainframeHQ/erebos/blob/132511b7a66563631db48af369540462e4af7e57/docs/timeline-spec.md) and [examples](https://github.com/MainframeHQ/erebos/blob/132511b7a66563631db48af369540462e4af7e57/docs/timeline-examples.md), please let me know if you have any comments or ideas for simple examples to add.

@agazso do you please have any feedback about this thread and the implementation changes? It doesn't provide very high-level features but hopefully it can be used as a basis for more advanced use cases.

@jpeletier is there any public link to ethergit or your implementation of the protocol I could refer to please?

**Comment by agazso** [comment]
Looks good to me. Looking at this document
https://github.com/MainframeHQ/erebos/blob/132511b7a66563631db48af369540462e4af7e57/docs/timeline-spec.md

I have one question:
- Is type can be different from `application/json`? Since per definition `content` is any valid JSON type?

**Comment by jpeletier** [comment]
> Regarding the `protocol`, maybe we could define how it can be extended? For example could it be `timeline/ethergit` and `timeline/mainframe` assuming we add custom "vendor" fields or rules for `references` for example, or something more like `timeline+git`, `timeline+json-ld+did`, etc. as "standard" sub-protocols that could be handled by other libraries in a generic way?

I would assume any differences among different uses of timeline should fall into whatever is in the `content` field, not change any other thing

**Comment by jpeletier** [comment]
> Is type can be different from application/json? Since per definition content is any valid JSON type?

Content by definition is any valid JSON type. What should be in the `content` field is something that hints you how to further interpret that JSON. For example, content could be a  "new post", "profile info", etc. It wouldn't have to be a mime type.

**Comment by jpeletier** [comment]
> is there any public link to ethergit or your implementation of the protocol I could refer to please?

Not yet. I would like to carve out the Go Timeline implementation as an external library so everyone can use it.

**Comment by PaulLeCam** [comment]
OK so the only `protocol` value accepted should be `timeline`, if there are forks of the protocol using a different value it wouldn't be compatible with the base protocol, I think that makes things simpler for now.

Regarding the `type` yes I imagine we could have something like:
```js
{
  ...
  type: 'text/html',
  content: '<p>Hello</p>'
}
```
So the `content` value is a valid JSON string, but the `type` provides more specific information about it.

Regarding the Go implementation, sounds great if you have plans to provide it as a separate library! Please let me know once it's available so I can add it to our docs.

**Comment by jpeletier** [comment]
> So the content value is a valid JSON string, but the type provides more specific information about it.

No, the `content` field is actual JSON, not a string containing JSON:

```javascript
{
  ...
  type: 'mytype',
  content: { myfield : "my value" } 
}
```

Though a standalone string is also valid JSON.

**Comment by PaulLeCam** [comment]
Yes I just meant it's a JSON string in my example where the `type` is set to `text/html`.
I agree for custom `type` values, any valid JSON can be set as `content`.
